2024-01-03 20:17:51,925 [INFO]: 2024-01-03 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-03 20:18:15,810 [WARNING]: parent_id as a parameter of constructor is being deprecated.
2024-01-03 20:18:15,814 [WARNING]: `remote_create` is being deprecated, please update your code with new function.
2024-01-03 20:18:15,815 [WARNING]: parent_id is being deprecated.
2024-01-03 20:18:15,815 [WARNING]: parent_id is being deprecated.
2024-01-03 20:18:15,815 [WARNING]: parent_id is being deprecated.
2024-01-03 20:18:19,112 [WARNING]: parent_id as a parameter of constructor is being deprecated.
2024-01-03 20:18:20,576 [ERROR]: 2024-01-03 - 'Influencers_cases/test_draft.py::Test_Draft::test_draft[SOCIAL POST]' finished with outcome: failed
2024-01-04 00:14:24,156 [INFO]: 2024-01-04 - 'Influencers_cases/test_report_generation.py::Test_report_generate::test_report_generate' finished with outcome: passed
2024-01-04 00:56:42,066 [INFO]: 2024-01-04 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-04 00:56:57,411 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3f905b5e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23aeea06ba202e9ea1fba66a9beeaa90
2024-01-04 00:56:57,412 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3f9478430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23aeea06ba202e9ea1fba66a9beeaa90
2024-01-04 00:56:57,413 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3f94782e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23aeea06ba202e9ea1fba66a9beeaa90
2024-01-04 00:58:50,396 [INFO]: 2024-01-04 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-04 00:59:23,207 [WARNING]: parent_id as a parameter of constructor is being deprecated.
2024-01-04 00:59:23,213 [WARNING]: `remote_create` is being deprecated, please update your code with new function.
2024-01-04 00:59:23,214 [WARNING]: parent_id is being deprecated.
2024-01-04 00:59:23,214 [WARNING]: parent_id is being deprecated.
2024-01-04 00:59:23,214 [WARNING]: parent_id is being deprecated.
2024-01-04 00:59:25,660 [WARNING]: parent_id as a parameter of constructor is being deprecated.
2024-01-04 00:59:26,765 [ERROR]: 2024-01-04 - 'Influencers_cases/test_draft.py::Test_Draft::test_draft[SOCIAL POST]' finished with outcome: failed
2024-01-04 01:02:36,120 [INFO]: 2024-01-04 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-04 01:03:00,322 [WARNING]: parent_id as a parameter of constructor is being deprecated.
2024-01-04 01:03:00,326 [WARNING]: `remote_create` is being deprecated, please update your code with new function.
2024-01-04 01:03:00,327 [WARNING]: parent_id is being deprecated.
2024-01-04 01:03:00,327 [WARNING]: parent_id is being deprecated.
2024-01-04 01:03:00,327 [WARNING]: parent_id is being deprecated.
2024-01-04 01:03:15,433 [INFO]: 2024-01-04 - 'Influencers_cases/test_draft.py::Test_Draft::test_draft[SOCIAL POST]' finished with outcome: passed
2024-01-05 17:07:45,752 [INFO]: 2024-01-05 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-05 17:08:05,546 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-05 17:08:40,320 [ERROR]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: failed
2024-01-05 17:09:15,275 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-05 17:09:19,835 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-05 17:12:40,475 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e850ad00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2debf2150b01e57ae79d8bd63251f4f3
2024-01-05 17:12:40,477 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e88d0520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2debf2150b01e57ae79d8bd63251f4f3
2024-01-05 17:12:40,478 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e88d00d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2debf2150b01e57ae79d8bd63251f4f3
2024-01-05 17:13:30,216 [INFO]: 2024-01-05 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-05 17:13:51,720 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-05 17:14:27,102 [ERROR]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: failed
2024-01-05 17:15:00,765 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-05 17:15:05,408 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-05 17:15:54,802 [INFO]: 2024-01-05 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-05 17:16:13,297 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-05 17:16:46,762 [ERROR]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: failed
2024-01-05 17:17:33,045 [ERROR]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: failed
2024-01-05 17:17:36,029 [INFO]: 2024-01-05 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-10 18:34:53,420 [INFO]: 2024-01-10 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-10 18:35:16,377 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-10 18:35:50,470 [ERROR]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: failed
2024-01-10 18:36:28,174 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-10 18:36:30,441 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-10 18:42:37,354 [INFO]: 2024-01-10 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-10 18:42:57,983 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-10 18:43:39,617 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-10 18:44:16,089 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-10 18:44:20,899 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-10 21:07:53,883 [INFO]: 2024-01-10 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-10 21:08:15,058 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-10 21:08:54,400 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-10 21:09:28,968 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-10 21:09:31,567 [INFO]: 2024-01-10 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-11 22:08:34,818 [INFO]: 2024-01-11 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-11 22:08:56,871 [INFO]: 2024-01-11 - 'Influencers_cases/test_Correction_draft.py::Test_CorrectionDraft::test_Correction_draft' finished with outcome: passed
2024-01-15 19:56:01,274 [INFO]: 2024-01-15 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-15 19:56:20,674 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-15 19:56:43,190 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-15 19:57:09,336 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-15 19:57:11,261 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-15 19:58:45,925 [INFO]: 2024-01-15 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-15 19:59:06,007 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-15 19:59:21,016 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-15 20:00:06,132 [ERROR]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: failed
2024-01-15 20:00:33,908 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-15 20:03:50,241 [INFO]: 2024-01-15 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-15 20:04:15,209 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-15 20:04:31,389 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-15 20:05:16,181 [ERROR]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: failed
2024-01-15 20:05:19,502 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-15 20:07:58,230 [INFO]: 2024-01-15 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-15 20:08:16,116 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-15 20:08:29,952 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-15 20:09:39,818 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-15 20:09:42,087 [INFO]: 2024-01-15 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-22 15:41:44,321 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:42:01,255 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:44:27,836 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:44:44,708 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:45:26,242 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:45:43,244 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:47:53,272 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:48:15,281 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:48:53,018 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:49:12,967 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:52:26,038 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:52:47,493 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:54:37,003 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:54:56,238 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 15:57:20,979 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 15:57:26,820 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 16:40:40,816 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 16:40:58,989 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 17:42:55,868 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 17:43:43,317 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 17:45:11,299 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 17:45:27,997 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 17:48:35,702 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdf7d004c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/f196f3dcc69d1da5f9f43469d216b298
2024-01-22 17:48:35,704 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdf7d00670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/f196f3dcc69d1da5f9f43469d216b298
2024-01-22 17:48:35,705 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdf7d002b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/f196f3dcc69d1da5f9f43469d216b298
2024-01-22 17:50:39,655 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 17:51:20,387 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 18:17:49,061 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd184e64c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6cf5d82d7802bbb6af2c1b5dc555631e
2024-01-22 18:17:49,064 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd184e6670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6cf5d82d7802bbb6af2c1b5dc555631e
2024-01-22 18:17:49,067 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd184e62b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6cf5d82d7802bbb6af2c1b5dc555631e
2024-01-22 18:18:23,664 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 18:19:17,705 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 18:20:08,283 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 18:21:03,245 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 18:22:39,543 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5e9ded5e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ef5c94bd8b567aef141182c289412a4
2024-01-22 18:22:39,547 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5e9ded550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ef5c94bd8b567aef141182c289412a4
2024-01-22 18:22:39,549 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5e9ded310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ef5c94bd8b567aef141182c289412a4
2024-01-22 18:23:37,665 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 18:24:21,170 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 18:25:21,016 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 18:26:05,852 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 18:27:08,540 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 18:28:12,370 [INFO]: 2024-01-22 - 'Influencers_cases/test_sign_brief.py::Test_Sign_brief::test_sign_brief[SOCIAL POST]' finished with outcome: passed
2024-01-22 23:00:17,273 [ERROR]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: failed
2024-01-22 23:04:33,829 [INFO]: 2024-01-22 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-22 23:09:07,357 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc089cea580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/76546713f680042b90552e13bd43cebf
2024-01-22 23:09:07,362 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc089cea400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/76546713f680042b90552e13bd43cebf
2024-01-22 23:09:07,363 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc089cea670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/76546713f680042b90552e13bd43cebf
2024-01-22 23:09:42,571 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf54cc05e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/fad330e3ffa4d82fc62317e117a196ff
2024-01-22 23:09:42,576 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf54cc0430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/fad330e3ffa4d82fc62317e117a196ff
2024-01-22 23:09:42,579 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf54cc02b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/fad330e3ffa4d82fc62317e117a196ff
2024-01-22 23:24:54,423 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb474e65e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/65b1c98d9b500abe8dfd7079cf9dc36b
2024-01-22 23:24:54,425 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb474e6430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/65b1c98d9b500abe8dfd7079cf9dc36b
2024-01-22 23:24:54,426 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb474e6310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/65b1c98d9b500abe8dfd7079cf9dc36b
2024-01-23 11:23:13,558 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf20c47190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5d1b00ad972e784f7f84a953000d303d
2024-01-23 11:23:13,560 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf20c47fd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5d1b00ad972e784f7f84a953000d303d
2024-01-23 11:23:13,562 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf20c47df0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5d1b00ad972e784f7f84a953000d303d
2024-01-23 11:23:52,470 [INFO]: 2024-01-23 - 'Influencers_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-23 11:24:13,772 [INFO]: 2024-01-23 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_pinterest_author' finished with outcome: passed
2024-01-23 11:24:52,982 [INFO]: 2024-01-23 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_facebook_author' finished with outcome: passed
2024-01-23 11:25:16,280 [INFO]: 2024-01-23 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_instagram_author' finished with outcome: passed
2024-01-23 11:25:18,919 [INFO]: 2024-01-23 - 'Influencers_cases/test_socail_pages.py::Test_Social::test_next_button' finished with outcome: passed
2024-01-23 16:13:21,416 [INFO]: 2024-01-23 16:13:21.416011 - 'Ahalogist_cases/test_login.py::TestLogin::test_login_page' finished with outcome: passed
2024-01-23 16:13:29,385 [INFO]: 2024-01-23 16:13:29.385214 - 'Ahalogist_cases/test_dynamic.py::Test_Dynamic::test_performance_influence' finished with outcome: passed
2024-01-23 16:15:35,339 [INFO]: 2024-01-23 16:15:35.339830 - 'Ahalogist_cases/test_login.py::TestLogin::test_login_page' finished with outcome: passed
2024-01-23 16:15:41,542 [INFO]: 2024-01-23 16:15:41.542226 - 'Ahalogist_cases/test_dynamic.py::Test_Dynamic::test_performance_influence' finished with outcome: passed
2024-01-23 16:16:56,368 [INFO]: 2024-01-23 16:16:56.366681 - 'Ahalogist_cases/test_login.py::TestLogin::test_login_page' finished with outcome: passed
2024-01-23 16:17:02,223 [INFO]: 2024-01-23 16:17:02.223627 - 'Ahalogist_cases/test_dynamic.py::Test_Dynamic::test_performance_influence' finished with outcome: passed
2024-01-30 14:26:57,967 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 14:27:02,025 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 14:33:55,121 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 14:34:08,778 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: passed
2024-01-30 16:03:16,763 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:03:51,191 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:07:44,494 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:08:18,404 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:10:29,049 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:11:03,279 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:15:24,747 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:15:58,951 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:19:03,535 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:19:38,119 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:26:15,138 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:26:51,062 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:30:06,116 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:30:21,236 [ERROR]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: failed
2024-01-30 16:40:27,026 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 16:40:41,875 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: passed
2024-01-30 17:00:48,241 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 17:01:03,291 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: passed
2024-01-30 17:01:13,724 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_login_page' finished with outcome: passed
2024-01-30 18:12:06,784 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 18:12:22,128 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: passed
2024-01-30 18:12:32,605 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_login_page' finished with outcome: passed
2024-01-30 19:24:34,470 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 19:24:49,427 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_login_page' finished with outcome: passed
2024-01-30 19:24:59,852 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_login_page' finished with outcome: passed
2024-01-30 19:25:11,533 [INFO]: 2024-01-30 - 'Promo_cases/test_creative.py::Test_Creative::test_login_page' finished with outcome: passed
2024-01-30 20:55:54,266 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 20:56:09,347 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-30 20:56:19,752 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-30 20:56:21,986 [ERROR]: 2024-01-30 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-30 20:59:06,653 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 20:59:22,302 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-30 20:59:32,769 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-30 20:59:47,202 [INFO]: 2024-01-30 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-30 21:02:41,898 [INFO]: 2024-01-30 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-30 21:02:56,825 [INFO]: 2024-01-30 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-30 21:03:07,302 [INFO]: 2024-01-30 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-30 21:03:21,686 [INFO]: 2024-01-30 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 19:44:42,997 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 19:44:58,030 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 19:45:08,494 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 19:45:10,670 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 19:47:44,499 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 19:47:59,759 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 19:48:10,298 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 19:48:22,808 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 19:50:44,317 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 19:50:59,211 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 19:51:09,706 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 19:51:22,009 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 19:55:16,231 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 19:55:31,792 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 19:55:42,343 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 19:56:05,335 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 19:56:59,798 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 19:57:14,912 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 19:57:25,503 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 19:57:48,416 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:02:16,778 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:02:31,819 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:02:42,240 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:02:54,407 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:04:13,664 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:04:28,329 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:04:38,785 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:04:50,893 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:06:03,045 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:06:18,057 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:06:28,536 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:06:53,810 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:09:39,420 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:09:54,455 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:10:04,923 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:10:17,223 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:15:21,996 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:15:36,886 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:15:47,345 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:15:59,487 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:22:20,754 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:22:35,755 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:22:46,214 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:23:08,958 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:23:47,771 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:24:02,286 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:24:12,739 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:24:35,754 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:32:33,679 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:32:48,936 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:32:59,424 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:33:22,420 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:35:44,754 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:35:59,735 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:36:10,272 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:36:12,615 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:38:46,927 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:39:01,645 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:39:12,289 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:39:35,568 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 20:47:05,915 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:47:21,403 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:47:31,888 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:47:44,277 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:55:02,456 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:55:19,732 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:55:30,222 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:55:42,290 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:57:38,462 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:57:53,383 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:58:03,855 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:58:16,177 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 20:59:11,943 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 20:59:26,982 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 20:59:37,480 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 20:59:39,522 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 21:00:03,466 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:00:18,907 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:00:29,401 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:00:52,348 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 21:06:41,317 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:06:56,284 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:07:06,759 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:07:29,730 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 21:09:37,268 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e7f36d280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ae907d729cded3a036a5a4d96c459673
2024-01-31 21:09:37,271 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e7f36d2e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ae907d729cded3a036a5a4d96c459673
2024-01-31 21:09:37,273 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e7f36df40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ae907d729cded3a036a5a4d96c459673
2024-01-31 21:11:06,995 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9326c31220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/abbe3e8b2ddb31522a4837e5b1fd7e4c
2024-01-31 21:11:06,997 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9326c31280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/abbe3e8b2ddb31522a4837e5b1fd7e4c
2024-01-31 21:11:06,998 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9326c31ee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/abbe3e8b2ddb31522a4837e5b1fd7e4c
2024-01-31 21:13:42,794 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:13:58,643 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:14:09,182 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:14:32,676 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 21:21:52,085 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff3b5c32220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/1b082ca2a5d2e88a0f507b6525be840c
2024-01-31 21:21:52,088 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff3b5c32280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/1b082ca2a5d2e88a0f507b6525be840c
2024-01-31 21:21:52,090 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff3b5c32ee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/1b082ca2a5d2e88a0f507b6525be840c
2024-01-31 21:25:40,891 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc086c31280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/442a3cf446cf8d929ddfca6ef049adb8
2024-01-31 21:25:40,893 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc086c312e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/442a3cf446cf8d929ddfca6ef049adb8
2024-01-31 21:25:40,894 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc086c31f40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/442a3cf446cf8d929ddfca6ef049adb8
2024-01-31 21:30:20,118 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2d6c30280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/40b30d59c7a9a95235d3d5d334952763
2024-01-31 21:30:20,120 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2d6c302e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/40b30d59c7a9a95235d3d5d334952763
2024-01-31 21:30:20,122 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2d6c30f40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/40b30d59c7a9a95235d3d5d334952763
2024-01-31 21:33:34,621 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:33:49,723 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:34:00,224 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:34:23,250 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 21:43:31,469 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:43:46,870 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:44:17,307 [ERROR]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: failed
2024-01-31 21:44:26,746 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 21:44:53,973 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:45:08,938 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:45:19,380 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:45:41,775 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 21:57:42,893 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 21:57:58,002 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 21:58:08,506 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 21:58:22,590 [INFO]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-01-31 22:08:54,219 [ERROR]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: failed
2024-01-31 22:09:24,875 [ERROR]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-01-31 22:09:55,439 [ERROR]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: failed
2024-01-31 22:10:26,198 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 22:19:15,554 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 22:19:30,604 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 22:19:41,075 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 22:19:43,148 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 22:25:32,633 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 22:25:47,643 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 22:25:58,100 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 22:26:00,330 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-01-31 22:27:45,775 [INFO]: 2024-01-31 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-01-31 22:28:00,794 [INFO]: 2024-01-31 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-01-31 22:28:11,539 [INFO]: 2024-01-31 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-01-31 22:28:13,756 [ERROR]: 2024-01-31 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:03:19,799 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:03:50,327 [ERROR]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: failed
2024-02-05 20:04:04,043 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7febcfd84580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2ec2741f27b1640b4eefb469136ea5a2
2024-02-05 20:04:04,044 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7febd0114040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2ec2741f27b1640b4eefb469136ea5a2
2024-02-05 20:04:04,045 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7febd00945b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2ec2741f27b1640b4eefb469136ea5a2
2024-02-05 20:04:54,672 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:05:10,909 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3bfd79df0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/06d19a21c767184af821d77031026e90
2024-02-05 20:05:10,910 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3c0113490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/06d19a21c767184af821d77031026e90
2024-02-05 20:05:10,912 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3c01132e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/06d19a21c767184af821d77031026e90
2024-02-05 20:07:21,705 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:07:51,435 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a251e700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/0d67a065891b1289ad25d16a03ed3865
2024-02-05 20:07:51,438 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a2883400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/0d67a065891b1289ad25d16a03ed3865
2024-02-05 20:07:51,441 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a2883250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/0d67a065891b1289ad25d16a03ed3865
2024-02-05 20:08:52,439 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:09:27,652 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 20:09:34,965 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb54855e700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/13d17b23bca4e04484116d1e173464ac
2024-02-05 20:09:34,967 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb54891c190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/13d17b23bca4e04484116d1e173464ac
2024-02-05 20:09:34,968 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb548898f10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/13d17b23bca4e04484116d1e173464ac
2024-02-05 20:10:14,992 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:10:49,201 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 20:11:00,036 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc836d1f700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b307a1e9838ec518cedb35a63648a47b
2024-02-05 20:11:00,038 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8370f4100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b307a1e9838ec518cedb35a63648a47b
2024-02-05 20:11:00,039 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc837077eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b307a1e9838ec518cedb35a63648a47b
2024-02-05 20:11:59,249 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:12:16,822 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc35cd1f700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e1f8925166a78cd86dd14eace4da1c46
2024-02-05 20:12:16,823 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc35d077730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e1f8925166a78cd86dd14eace4da1c46
2024-02-05 20:12:16,825 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc35d077430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e1f8925166a78cd86dd14eace4da1c46
2024-02-05 20:14:48,254 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:15:22,616 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 20:15:30,402 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa35ed1f700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4035b2e25ad2f826dd9dd2f25c9dd106
2024-02-05 20:15:30,403 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa35f0f21c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4035b2e25ad2f826dd9dd2f25c9dd106
2024-02-05 20:15:30,404 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa35f075f10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4035b2e25ad2f826dd9dd2f25c9dd106
2024-02-05 20:24:59,009 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:25:28,230 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5d2d1f730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/58fd0ec780cc5b0b950ca6a8bc343503
2024-02-05 20:25:28,231 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5d30af700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/58fd0ec780cc5b0b950ca6a8bc343503
2024-02-05 20:25:28,232 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5d30af580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/58fd0ec780cc5b0b950ca6a8bc343503
2024-02-05 20:25:58,110 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:26:18,040 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff09cd5f700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbe910784a097cb34057e63350bf8ad
2024-02-05 20:26:18,041 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff09d0ae4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbe910784a097cb34057e63350bf8ad
2024-02-05 20:26:18,042 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff09d0ae340>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbe910784a097cb34057e63350bf8ad
2024-02-05 20:29:38,326 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:29:55,286 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecf3d5f7f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/239d717b33f7a3069add2812e3fe7c67
2024-02-05 20:29:55,287 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecf410a4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/239d717b33f7a3069add2812e3fe7c67
2024-02-05 20:29:55,289 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecf410a340>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/239d717b33f7a3069add2812e3fe7c67
2024-02-05 20:31:17,124 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:31:51,251 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 20:32:21,702 [ERROR]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: failed
2024-02-05 20:32:52,417 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:34:29,987 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:34:51,711 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa95ad5f730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d473689e53c17e653e96cc36108e303f
2024-02-05 20:34:51,712 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa95b09f910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d473689e53c17e653e96cc36108e303f
2024-02-05 20:34:51,714 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa95b09fbb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d473689e53c17e653e96cc36108e303f
2024-02-05 20:36:03,014 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:36:17,784 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:36:28,201 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:36:40,139 [INFO]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-05 20:39:01,481 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:39:16,788 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:39:27,191 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:39:29,217 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:46:51,828 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:47:06,978 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:47:17,373 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:47:19,497 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:51:01,111 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:51:15,764 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:51:26,177 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:51:28,083 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:51:58,161 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:52:12,757 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:52:23,193 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:52:25,328 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:52:49,912 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:53:04,880 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:53:15,380 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:53:17,743 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 20:54:12,427 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 20:54:27,416 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 20:54:37,824 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 20:54:39,896 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:01:36,610 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:01:51,889 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:02:02,281 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:02:04,446 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:09:15,989 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:09:30,726 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:09:41,124 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:09:43,086 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:13:15,439 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:13:30,584 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:13:41,016 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:13:42,679 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:18:27,473 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fce834311c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/986d977174fdf777cf1ef6f9113e2050
2024-02-05 21:18:27,475 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fce83431220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/986d977174fdf777cf1ef6f9113e2050
2024-02-05 21:18:27,476 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fce83431e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/986d977174fdf777cf1ef6f9113e2050
2024-02-05 21:21:26,082 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa82c36c130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5b666c309b5bce61d39f2a9441845b54
2024-02-05 21:21:26,083 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa82c36cfd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5b666c309b5bce61d39f2a9441845b54
2024-02-05 21:21:26,084 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa82c36ce50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5b666c309b5bce61d39f2a9441845b54
2024-02-05 21:22:54,434 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:23:25,089 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 21:23:30,564 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc7e44ecd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e941248c62e7151caddf1373135c5b61
2024-02-05 21:23:30,565 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc7e944400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e941248c62e7151caddf1373135c5b61
2024-02-05 21:23:30,566 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc7e7add60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e941248c62e7151caddf1373135c5b61
2024-02-05 21:25:46,080 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:26:00,925 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:26:11,375 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:26:13,720 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:27:43,907 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:27:58,822 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:28:09,257 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:28:11,387 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:28:42,374 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:28:57,455 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:29:07,877 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:29:09,996 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:32:21,875 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:32:36,955 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:32:47,328 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:32:49,363 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:33:22,783 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:33:38,065 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:33:48,498 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:34:00,572 [INFO]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-05 21:36:34,976 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff45d4311f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6455a89dec1699f197fa2e1128ab8e3b
2024-02-05 21:36:34,977 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff45d431250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6455a89dec1699f197fa2e1128ab8e3b
2024-02-05 21:36:34,978 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff45d431eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6455a89dec1699f197fa2e1128ab8e3b
2024-02-05 21:37:59,072 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:38:14,114 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:38:24,539 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:38:26,549 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:38:58,343 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:39:13,129 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:39:23,509 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:39:35,446 [INFO]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-05 21:46:28,301 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:46:45,519 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:46:55,998 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:47:24,136 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdbd9d78dc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c4154002474d85013ab58cc72c60dfea
2024-02-05 21:47:24,137 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdbda1176d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c4154002474d85013ab58cc72c60dfea
2024-02-05 21:47:24,139 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdbda117e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c4154002474d85013ab58cc72c60dfea
2024-02-05 21:48:53,376 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:49:07,852 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:49:18,281 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:49:50,430 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 21:56:00,470 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:56:15,220 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:56:25,647 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:56:33,062 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802a44eca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4795edf5a64d12810168e09099bd6972
2024-02-05 21:56:33,064 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802a7fd8e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4795edf5a64d12810168e09099bd6972
2024-02-05 21:56:33,065 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802a7fda00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4795edf5a64d12810168e09099bd6972
2024-02-05 21:57:08,912 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 21:57:23,811 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 21:57:34,298 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 21:58:06,592 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 22:05:41,201 [ERROR]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: failed
2024-02-05 22:06:11,907 [ERROR]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-05 22:06:19,651 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feffad3dd00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/86f90a59a4be61613a8538ff63ce66ba
2024-02-05 22:06:19,653 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feffb0ef310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/86f90a59a4be61613a8538ff63ce66ba
2024-02-05 22:06:19,654 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feffaff6c40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/86f90a59a4be61613a8538ff63ce66ba
2024-02-05 22:10:12,138 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 22:10:27,314 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 22:10:38,586 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 22:11:10,859 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 22:19:10,579 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e41c310a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/828e05598c9b7dddc5c4bf5d3fdf66a9
2024-02-05 22:19:10,580 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e41c31e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/828e05598c9b7dddc5c4bf5d3fdf66a9
2024-02-05 22:19:10,582 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e41c31d00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/828e05598c9b7dddc5c4bf5d3fdf66a9
2024-02-05 22:20:06,998 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 22:20:21,799 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 22:20:32,272 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 22:20:34,681 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-05 22:23:35,461 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87a25fb850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ff9366500a07f1fce48e7ee70e231ae
2024-02-05 22:23:35,462 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87a25fb460>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ff9366500a07f1fce48e7ee70e231ae
2024-02-05 22:23:35,463 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87a25fb2e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ff9366500a07f1fce48e7ee70e231ae
2024-02-05 22:25:34,478 [INFO]: 2024-02-05 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-05 22:25:49,360 [INFO]: 2024-02-05 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-05 22:25:59,811 [INFO]: 2024-02-05 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-05 22:26:32,154 [ERROR]: 2024-02-05 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 17:15:06,470 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:15:24,067 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:15:34,669 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:16:00,059 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3edc04d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ca64bc0315ccbc121175f9f0cf83c54b
2024-02-06 17:16:00,067 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3edffa490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ca64bc0315ccbc121175f9f0cf83c54b
2024-02-06 17:16:00,070 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3edffa340>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ca64bc0315ccbc121175f9f0cf83c54b
2024-02-06 17:21:45,966 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:22:02,853 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:22:13,341 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:22:16,523 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 17:25:41,886 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:25:58,633 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:26:09,278 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:26:21,779 [INFO]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-06 17:31:06,874 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:31:25,254 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:31:35,927 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:31:38,364 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 17:32:36,152 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:32:53,453 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:33:03,975 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:33:11,803 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 17:47:44,244 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 17:48:00,359 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 17:48:10,878 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 17:48:18,528 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:07:21,092 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:07:37,687 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:07:48,174 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:08:26,098 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:15:27,056 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:15:43,035 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:15:53,435 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:16:26,051 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:19:53,744 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:20:09,143 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:20:19,612 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:21:12,579 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:23:15,394 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:23:31,369 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:23:41,826 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:27:45,865 [INFO]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-06 18:29:36,564 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:29:52,643 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:30:03,065 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:30:55,734 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:36:51,791 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:37:09,040 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:37:19,498 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:39:04,331 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ef3c4cd90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3ec1681e2491f83122a2f9104c5865bf
2024-02-06 18:39:04,335 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ef3f05490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3ec1681e2491f83122a2f9104c5865bf
2024-02-06 18:39:04,340 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ef3f05310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3ec1681e2491f83122a2f9104c5865bf
2024-02-06 18:41:40,876 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:41:56,960 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:42:07,415 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:42:09,808 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:42:48,195 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:43:04,102 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:43:14,547 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:48:05,902 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:50:26,489 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:50:42,372 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:50:52,806 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:50:55,314 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 18:52:30,911 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 18:52:46,486 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 18:52:56,983 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 18:57:59,782 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 19:01:19,144 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 19:01:34,640 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 19:01:45,137 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 19:02:17,925 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 19:19:10,908 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 19:19:26,765 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 19:19:37,227 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 19:19:39,150 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 19:22:30,864 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 19:22:47,018 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 19:22:57,427 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 19:22:59,635 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 19:23:57,871 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 19:24:14,151 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 19:24:24,835 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 19:24:28,919 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 19:25:15,593 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 19:25:33,141 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 19:25:43,650 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 19:25:46,327 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 20:35:03,520 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 20:35:20,777 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 20:35:51,688 [ERROR]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: failed
2024-02-06 20:36:00,166 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-06 20:45:30,548 [INFO]: 2024-02-06 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-06 20:45:46,411 [INFO]: 2024-02-06 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-06 20:46:20,693 [INFO]: 2024-02-06 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-06 20:46:23,108 [ERROR]: 2024-02-06 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 18:50:02,813 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 18:50:18,193 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 18:50:28,596 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 18:50:30,622 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 18:51:13,466 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 18:51:28,575 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 18:51:38,974 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 18:51:41,004 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 18:53:46,381 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 18:54:01,393 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 18:54:11,858 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 18:54:14,505 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:02:03,388 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:02:18,261 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:02:28,729 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:02:31,065 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:05:20,849 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:05:35,912 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:05:46,427 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:06:24,095 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:08:09,230 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:08:24,724 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:08:35,133 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:08:42,342 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:10:01,415 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:10:16,770 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:10:27,283 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:10:44,492 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:13:55,252 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:14:10,348 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:14:20,734 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:14:59,549 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-07 19:22:12,570 [INFO]: 2024-02-07 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-07 19:22:27,349 [INFO]: 2024-02-07 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-07 19:22:37,737 [INFO]: 2024-02-07 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-07 19:23:15,036 [ERROR]: 2024-02-07 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 14:27:11,522 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 14:27:27,778 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 14:27:38,387 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 14:27:40,720 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 14:29:53,849 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 14:30:09,867 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 14:30:20,288 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 14:30:43,800 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 14:38:46,930 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 14:39:01,976 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 14:39:12,403 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 14:39:24,660 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 14:42:31,472 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 14:42:47,371 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 14:42:57,795 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 14:43:00,106 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 14:44:45,999 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 14:45:01,021 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 14:45:11,422 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 14:45:34,768 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:21:05,199 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:21:22,092 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:21:32,666 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:21:58,492 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:22:32,480 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:24:33,996 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:24:51,689 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:25:02,140 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:25:28,493 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:25:32,404 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:30:03,768 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:30:20,454 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:30:30,968 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:30:57,779 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:31:43,542 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:35:18,310 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:35:34,826 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:35:45,353 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:36:11,894 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:36:51,353 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:37:40,988 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:37:57,608 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:38:08,081 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:38:10,598 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 16:38:50,835 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:47:30,194 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:47:46,065 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:47:56,760 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:48:24,526 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:48:39,142 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 16:51:28,922 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:51:44,398 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:51:54,782 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:52:18,963 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:52:20,620 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 16:56:43,961 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 16:56:58,915 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 16:57:09,337 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 16:57:31,946 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 16:57:44,728 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 17:08:00,978 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:08:16,258 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:08:26,736 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:08:50,633 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:09:03,554 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 17:10:00,365 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:10:16,663 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:10:27,053 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:10:29,529 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 17:11:09,286 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb7c205b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9c965a882422ad4c4da074e095c5ef80
2024-02-08 17:11:09,288 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb8170040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9c965a882422ad4c4da074e095c5ef80
2024-02-08 17:11:09,293 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb80b1ee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9c965a882422ad4c4da074e095c5ef80
2024-02-08 17:13:46,556 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:14:02,390 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:14:12,888 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:14:38,271 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:14:40,468 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 17:15:16,512 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:15:32,634 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:15:43,154 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:16:11,317 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:16:23,534 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 17:25:12,009 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:25:29,282 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:25:39,841 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:26:11,255 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:26:51,341 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 17:32:54,307 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:33:09,905 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:33:20,453 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:33:43,899 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:34:24,761 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 17:37:45,551 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:38:03,172 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:38:13,624 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:38:38,651 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:38:53,683 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 17:42:32,428 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:42:41,376 [ERROR]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-08 17:42:51,340 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefc3461490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bf7c6abd6094e35d55baf69a739921d3
2024-02-08 17:42:51,341 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefc36ed7c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bf7c6abd6094e35d55baf69a739921d3
2024-02-08 17:42:51,344 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefc36ed4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bf7c6abd6094e35d55baf69a739921d3
2024-02-08 17:43:42,538 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:43:50,966 [ERROR]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-08 17:43:56,273 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6b7c61520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2131babf91745a7d06275b477d4bd085
2024-02-08 17:43:56,276 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6b805d040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2131babf91745a7d06275b477d4bd085
2024-02-08 17:43:56,278 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6b7fe5d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2131babf91745a7d06275b477d4bd085
2024-02-08 17:49:30,940 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:49:41,832 [ERROR]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-08 17:49:44,433 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1c74205b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a37fc5aa6e326ca21d908c034938c09c
2024-02-08 17:49:44,436 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1c7839220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a37fc5aa6e326ca21d908c034938c09c
2024-02-08 17:49:44,437 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1c78000a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a37fc5aa6e326ca21d908c034938c09c
2024-02-08 17:51:45,294 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:52:05,342 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:52:15,908 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:52:42,873 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:52:57,924 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 17:56:17,476 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:56:28,333 [ERROR]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: failed
2024-02-08 17:56:49,270 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf01c2a4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9661451d070859a8aac94ebd34e51cc7
2024-02-08 17:56:49,273 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf01ffb790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9661451d070859a8aac94ebd34e51cc7
2024-02-08 17:56:49,276 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf01ffb6a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9661451d070859a8aac94ebd34e51cc7
2024-02-08 17:57:40,976 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 17:58:00,410 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 17:58:11,356 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 17:58:45,203 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 17:58:54,612 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 18:05:00,615 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:05:20,673 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:05:31,709 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:06:06,605 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:06:30,468 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 18:10:51,964 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:11:12,361 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:11:23,575 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:11:57,179 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:12:20,878 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 18:18:18,979 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:18:35,931 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:18:46,384 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:19:14,024 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:19:59,314 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 18:21:34,555 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:21:52,880 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:22:03,348 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:22:30,372 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:22:52,882 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 18:25:08,246 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:25:17,535 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:25:18,595 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:25:21,348 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 18:25:44,907 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe376c198b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e335cec085c870bbc04adb2ae9c3c3b7
2024-02-08 18:25:44,910 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe37705ad60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e335cec085c870bbc04adb2ae9c3c3b7
2024-02-08 18:25:44,912 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe37705adf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e335cec085c870bbc04adb2ae9c3c3b7
2024-02-08 18:26:30,635 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:26:40,755 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:26:41,885 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:26:45,938 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 18:26:51,237 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad1647afd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5396dc8b03cffde5fa898bdcc0162cb2
2024-02-08 18:26:51,239 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad1647ae50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5396dc8b03cffde5fa898bdcc0162cb2
2024-02-08 18:26:51,241 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad1645e970>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5396dc8b03cffde5fa898bdcc0162cb2
2024-02-08 18:27:45,669 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:27:53,707 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:27:55,101 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:28:13,340 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:28:15,138 [ERROR]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-08 18:29:12,278 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:29:21,290 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:29:22,405 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:29:26,890 [ERROR]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-08 18:29:31,220 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad92461610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff673da220bd33d19bcb6322afaf46ac
2024-02-08 18:29:31,224 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad9288fca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff673da220bd33d19bcb6322afaf46ac
2024-02-08 18:29:31,228 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad92781eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff673da220bd33d19bcb6322afaf46ac
2024-02-08 18:30:07,225 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:30:14,230 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:30:19,855 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:30:48,012 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:31:12,649 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-08 18:31:43,476 [INFO]: 2024-02-08 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-08 18:31:54,800 [INFO]: 2024-02-08 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-08 18:32:00,929 [INFO]: 2024-02-08 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-08 18:32:36,477 [INFO]: 2024-02-08 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-08 18:33:01,924 [INFO]: 2024-02-08 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 16:03:17,368 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 16:03:28,972 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 16:03:34,882 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 16:04:00,620 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 16:04:02,334 [ERROR]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-09 16:04:04,074 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 16:37:23,906 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 16:37:28,590 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 16:37:34,471 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 16:37:55,040 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 16:37:56,508 [ERROR]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-09 16:37:57,150 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 16:39:38,008 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 16:39:42,819 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 16:39:49,724 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 16:40:18,617 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 16:40:38,286 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 16:41:11,141 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 16:47:13,179 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 16:47:18,093 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 16:47:24,011 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 16:47:52,719 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 16:48:13,420 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 16:48:46,084 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 17:45:48,122 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 17:45:52,496 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 17:45:58,418 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 17:46:27,350 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 17:46:47,885 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 17:47:23,261 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 17:59:41,105 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 17:59:45,210 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 17:59:51,105 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:00:19,813 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:00:39,619 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:01:03,570 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf7352b7f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/41fe33cc055f13f63c8919f4eb81ea32
2024-02-09 18:01:03,571 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf7394c6a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/41fe33cc055f13f63c8919f4eb81ea32
2024-02-09 18:01:03,572 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf7394c3a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/41fe33cc055f13f63c8919f4eb81ea32
2024-02-09 18:03:45,574 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:03:50,686 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:03:56,600 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:04:25,412 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:04:46,183 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:05:30,693 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:06:03,868 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:06:08,643 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:06:14,626 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:06:16,549 [ERROR]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-09 18:07:02,391 [ERROR]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-09 18:07:04,049 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:07:25,819 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:07:31,092 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:07:43,177 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:08:12,282 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:08:32,364 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:08:42,873 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:11:15,830 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:11:21,137 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:11:27,056 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:11:55,805 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:12:05,928 [ERROR]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-09 18:12:07,313 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:12:31,113 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:12:35,816 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:12:41,337 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:13:10,222 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:13:30,987 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:13:32,420 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:17:46,279 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:17:50,913 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:17:56,793 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:18:26,138 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:18:56,273 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:19:01,697 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:20:02,711 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:20:07,481 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:20:13,427 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:20:42,558 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:21:13,738 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:21:29,442 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:25:21,520 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:25:26,565 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:25:32,482 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:26:01,897 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:26:33,064 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:27:13,115 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 18:29:50,378 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:29:55,770 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:30:01,393 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:30:30,275 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:31:00,445 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:31:21,604 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 18:33:50,650 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:33:55,602 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:34:01,490 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:34:30,262 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:35:00,678 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:35:15,225 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 18:36:40,103 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:36:44,592 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:36:50,529 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:36:52,453 [ERROR]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-09 18:37:11,642 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd486d6a820>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c42d32e2bc5b92edced251ce517d508c
2024-02-09 18:37:11,643 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4872150a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c42d32e2bc5b92edced251ce517d508c
2024-02-09 18:37:11,645 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd487199370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c42d32e2bc5b92edced251ce517d508c
2024-02-09 18:39:11,589 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:39:16,519 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:39:22,399 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:39:51,765 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:40:22,018 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:40:34,015 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 18:44:32,944 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:44:38,121 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:44:44,005 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:44:45,923 [ERROR]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: failed
2024-02-09 18:45:10,223 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda6b56a820>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/03dc7d40a9fdbe6602d8378f68ca63d0
2024-02-09 18:45:10,224 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda6ba1b0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/03dc7d40a9fdbe6602d8378f68ca63d0
2024-02-09 18:45:10,225 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda6b99e370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/03dc7d40a9fdbe6602d8378f68ca63d0
2024-02-09 18:45:32,156 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 18:45:36,802 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 18:45:42,691 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 18:46:12,100 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 18:46:42,803 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 18:47:21,346 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 19:17:34,511 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 19:17:39,749 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 19:17:45,776 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 19:18:14,678 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 19:18:44,852 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 19:18:58,337 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 19:19:09,811 [INFO]: 2024-02-09 - 'Promo_cases/test_tactics.py::Test_Tactics::test_creative_page' finished with outcome: passed
2024-02-09 19:26:21,362 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 19:26:25,817 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 19:26:31,973 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 19:27:01,032 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 19:27:31,167 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 19:27:44,653 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 19:27:56,237 [INFO]: 2024-02-09 - 'Promo_cases/test_tactics.py::Test_Tactics::test_creative_page' finished with outcome: passed
2024-02-09 20:40:19,609 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 20:40:26,710 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 20:40:32,709 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 20:41:02,452 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 20:41:23,303 [ERROR]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: failed
2024-02-09 20:41:24,775 [ERROR]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: failed
2024-02-09 20:41:29,426 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff421d58640>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/990b92c520783c17aade29be5f22310e
2024-02-09 20:41:29,427 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff42222d280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/990b92c520783c17aade29be5f22310e
2024-02-09 20:41:29,428 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff42222d400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/990b92c520783c17aade29be5f22310e
2024-02-09 20:41:49,382 [INFO]: 2024-02-09 - 'Promo_cases/test_login.py::Test_login::test_login_page' finished with outcome: passed
2024-02-09 20:41:56,680 [INFO]: 2024-02-09 - 'Promo_cases/test_IO_create.py::Test_IO::test_iocreate_page' finished with outcome: passed
2024-02-09 20:42:02,611 [INFO]: 2024-02-09 - 'Promo_cases/test_enable_promo.py::Test_Enable::test_enable_promo_page' finished with outcome: passed
2024-02-09 20:42:32,468 [INFO]: 2024-02-09 - 'Promo_cases/test_creative.py::Test_Creative::test_creative_page' finished with outcome: passed
2024-02-09 20:43:02,363 [INFO]: 2024-02-09 - 'Promo_cases/test_amp.py::Test_Amp::test_amp' finished with outcome: passed
2024-02-09 20:43:15,361 [INFO]: 2024-02-09 - 'Promo_cases/test_line.py::Test_line::test_line_page' finished with outcome: passed
2024-02-09 20:43:27,083 [INFO]: 2024-02-09 - 'Promo_cases/test_tactics.py::Test_Tactics::test_creative_page' finished with outcome: passed
